services:
  product_postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=productcataloglab'
      - 'POSTGRES_PASSWORD=productcatalogservice'
      - 'POSTGRES_USER=productcatalogservice'
    ports:
      - "5432:5432"
  accommodation_postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=accommodationdb'
      - 'POSTGRES_PASSWORD=accomodationservice'
      - 'POSTGRES_USER=accomodationservice'
    ports:
      - "5433:5433"
