apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accommodation-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: standard