@api = http://localhost:8080/api/v1/accommodations
@jwt =eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdG5hbWUiOiJLYW1pbCIsInJvbGUiOiJPV05FUiIsImxhc3RuYW1lIjoiV29kb3dza2kiLCJzdWIiOiJLYW1pbFdvZG93c2tpQGdtYWlsLmNvbSIsImlhdCI6MTc2ODEyNTAyNiwiZXhwIjoxNzY4MTI4NjI2fQ.rctfX1GlXVt7Je8hC7y2Bq5R3onuiWzfF3WIS_7aeiM

GET {{api}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

GET {{api}}?type=HOTEL

###

GET {{api}}/1

###

POST {{api}}
Content-Type: application/json

{
  "name": "Hotel Victoria",
  "description": "Nasza oferta stanowi doskonałą propozycję zarówno dla gości indywidualnych, biznesowych, jaki i grup konferencyjnych oraz turystycznych.",
  "city": "Lublin",
  "address": "Gabriela Narutowicza 23",
  "type": "HOSTEL",
  "features": ["Spa", "Plac zabaw", "Restauracja"]
}

###

PUT {{api}}/1
Content-Type: application/json

{
  "id": 1,
  "name": "Hotel Vdfzgdfictoryhjtia 79",
  "description": "Nasza oferta stanowi doskonałą propozycję zarówno dla gości indywidualnych, biznesowych, jaki i grup konferencyjnych oraz turystycznych.",
  "city": "Lubartów",
  "address": "Gabriela Narutowicza 23",
  "type": "HOSTEL",
  "features": ["Spa", "Plac zabaw", "Restauracja"]
}

###

DELETE {{api}}/2